Membership Payment updates
acm-uiuc/groot-desktop-frontend pull request #154
Opened 2017-11-09 20:27 UTC by bcongdon

- Added success page for after a member has paid
- Changed payment logic so a user doesn't need to be logged in to pay for membership

Marking as WIP because I still need to do an end-to-end test with the AD service

2017-11-09 20:35 UTC, sameetandpotatoes approved these changes
lgtm

2017-11-10 16:12 UTC, narendasan requested changes

2017-11-10 16:12 UTC, narendasan commented on app/controllers/credits.js
> +        req.flash('error', "Something went wrong with your payment. Please talk to someone in ACM Admin.");
Add an email here or link to the #userhelp slack channel

2017-11-10 16:12 UTC, narendasan commented on app/views/credits/credits_membership_success.ejs
> +    <p>Thanks for submitting your purchase for an ACM membership! It may take a little bit to get your membership registered on our end, so we appreciate your patience. Once your membership processin
change "you'll be able to access our intranet" to "you'll be able to access ACM's services" or something

2018-04-22 23:25 UTC, narendasan commented
@aashishkapur did you ever finish the AD service, would be nice to get this in before the end of the year

2018-04-22 23:42 UTC, bcongdon commented
Agreed...

2018-04-22 23:47 UTC, aashishkapur commented
Yeah, the service has been up for a while now, acm-uiuc/groot-users-service#22 needs to be merged

2018-04-23 00:29 UTC, narendasan commented
Looks like thats held up on copy needed @acm-uiuc/top4 is there anything else needed for the merge of the feature?

2023-04-08 17:27 UTC, closed without merging